#!/bin/sh
gemc \
-gcard=solid_CLEO_SIDIS_He3_other.gcard \
-DBHOST=$GEMC_HOST \
-HIT_PROCESS_LIST=solid \
-HALL_MATERIAL=Vacuum \
-USE_PHYSICSL=QGSP_BERT \
-RECORD_PASSBY=1 \
-FIELD_DIR=$GEMC_field \
-HALL_FIELD=solenoid_CLEO \
-INPUT_GEN_FILE="LUND,/home/zwzhao/work_halla/solid/solid_svn/solid/evgen/eicRate_20101102/output/SIDIS_He3/rate_solid_SIDIS_He3_pip_1e6.lund" \
-N=1e6 \
-OUTPUT="evio,background_solid_CLEO_SIDIS_He3_other_pip_1e6.evio" \
-USE_QT=0

# gemc \
# -gcard=solid_CLEO_SIDIS_He3_other.gcard \
# -DBHOST=$GEMC_HOST \
# -HIT_PROCESS_LIST=solid \
# -HALL_MATERIAL=Vacuum \
# -USE_PHYSICSL=QGSP_BERT \
# -RECORD_PASSBY=1 \
# -FIELD_DIR=$GEMC_field \
# -HALL_FIELD=solenoid_CLEO \
# -INPUT_GEN_FILE="LUND,/home/zwzhao/work_halla/solid/solid_svn/solid/evgen/eicRate_20101102/output/SIDIS_He3/rate_solid_SIDIS_He3_pim_1e6.lund" \
# -N=1e6 \
# -OUTPUT="evio,background_solid_CLEO_SIDIS_He3_other_pim_1e6.evio" \
# -USE_QT=0
# 
# 
# gemc \
# -gcard=solid_CLEO_SIDIS_He3_other.gcard \
# -DBHOST=$GEMC_HOST \
# -HIT_PROCESS_LIST=solid \
# -HALL_MATERIAL=Vacuum \
# -USE_PHYSICSL=QGSP_BERT \
# -RECORD_PASSBY=1 \
# -FIELD_DIR=$GEMC_field \
# -HALL_FIELD=solenoid_CLEO \
# -INPUT_GEN_FILE="LUND,/home/zwzhao/work_halla/solid/solid_svn/solid/evgen/eicRate_20101102/output/SIDIS_He3/rate_solid_SIDIS_He3_pi0_1e6.lund" \
# -N=1e6 \
# -OUTPUT="evio,background_solid_CLEO_SIDIS_He3_other_pi0_1e6.evio" \
# -USE_QT=0
# 
# gemc \
# -gcard=solid_CLEO_SIDIS_He3_other.gcard \
# -DBHOST=$GEMC_HOST \
# -HIT_PROCESS_LIST=solid \
# -HALL_MATERIAL=Vacuum \
# -USE_PHYSICSL=QGSP_BERT \
# -RECORD_PASSBY=1 \
# -FIELD_DIR=$GEMC_field \
# -HALL_FIELD=solenoid_CLEO \
# -INPUT_GEN_FILE="LUND,/home/zwzhao/work_halla/solid/solid_svn/solid/evgen/eicRate_20101102/output/SIDIS_He3/rate_solid_SIDIS_He3_Kp_1e6.lund" \
# -N=1e6 \
# -OUTPUT="evio,background_solid_CLEO_SIDIS_He3_other_Kp_1e6.evio" \
# -USE_QT=0
# 
# gemc \
# -gcard=solid_CLEO_SIDIS_He3_other.gcard \
# -DBHOST=$GEMC_HOST \
# -HIT_PROCESS_LIST=solid \
# -HALL_MATERIAL=Vacuum \
# -USE_PHYSICSL=QGSP_BERT \
# -RECORD_PASSBY=1 \
# -FIELD_DIR=$GEMC_field \
# -HALL_FIELD=solenoid_CLEO \
# -INPUT_GEN_FILE="LUND,/home/zwzhao/work_halla/solid/solid_svn/solid/evgen/eicRate_20101102/output/SIDIS_He3/rate_solid_SIDIS_He3_Km_1e6.lund" \
# -N=1e6 \
# -OUTPUT="evio,background_solid_CLEO_SIDIS_He3_other_Km_1e6.evio" \
# -USE_QT=0
# 
# gemc \
# -gcard=solid_CLEO_SIDIS_He3_other.gcard \
# -DBHOST=$GEMC_HOST \
# -HIT_PROCESS_LIST=solid \
# -HALL_MATERIAL=Vacuum \
# -USE_PHYSICSL=QGSP_BERT \
# -RECORD_PASSBY=1 \
# -FIELD_DIR=$GEMC_field \
# -HALL_FIELD=solenoid_CLEO \
# -INPUT_GEN_FILE="LUND,/home/zwzhao/work_halla/solid/solid_svn/solid/evgen/eicRate_20101102/output/SIDIS_He3/rate_solid_SIDIS_He3_Ks_1e6.lund" \
# -N=1e6 \
# -OUTPUT="evio,background_solid_CLEO_SIDIS_He3_other_Ks_1e6.evio" \
# -USE_QT=0
# 
# gemc \
# -gcard=solid_CLEO_SIDIS_He3_other.gcard \
# -DBHOST=$GEMC_HOST \
# -HIT_PROCESS_LIST=solid \
# -HALL_MATERIAL=Vacuum \
# -USE_PHYSICSL=QGSP_BERT \
# -RECORD_PASSBY=1 \
# -FIELD_DIR=$GEMC_field \
# -HALL_FIELD=solenoid_CLEO \
# -INPUT_GEN_FILE="LUND,/home/zwzhao/work_halla/solid/solid_svn/solid/evgen/eicRate_20101102/output/SIDIS_He3/rate_solid_SIDIS_He3_Kl_1e6.lund" \
# -N=1e6 \
# -OUTPUT="evio,background_solid_CLEO_SIDIS_He3_other_Kl_1e6.evio" \
# -USE_QT=0
# 
# gemc \
# -gcard=solid_CLEO_SIDIS_He3_other.gcard \
# -DBHOST=$GEMC_HOST \
# -HIT_PROCESS_LIST=solid \
# -HALL_MATERIAL=Vacuum \
# -USE_PHYSICSL=QGSP_BERT \
# -RECORD_PASSBY=1 \
# -FIELD_DIR=$GEMC_field \
# -HALL_FIELD=solenoid_CLEO \
# -INPUT_GEN_FILE="LUND,/home/zwzhao/work_halla/solid/solid_svn/solid/evgen/eicRate_20101102/output/SIDIS_He3/rate_solid_SIDIS_He3_p_1e6.lund" \
# -N=1e6 \
# -OUTPUT="evio,background_solid_CLEO_SIDIS_He3_other_p_1e6.evio" \
# -USE_QT=0
# 
# gemc \
# -gcard=solid_CLEO_SIDIS_He3_other.gcard \
# -DBHOST=$GEMC_HOST \
# -HIT_PROCESS_LIST=solid \
# -HALL_MATERIAL=Vacuum \
# -USE_PHYSICSL=QGSP_BERT \
# -RECORD_PASSBY=1 \
# -FIELD_DIR=$GEMC_field \
# -HALL_FIELD=solenoid_CLEO \
# -INPUT_GEN_FILE="LUND,/home/zwzhao/work_halla/solid/solid_svn/solid/evgen/eicRate_20101102/output/SIDIS_He3/rate_solid_SIDIS_He3_eES_1e6.lund" \
# -N=1e6 \
# -OUTPUT="evio,background_solid_CLEO_SIDIS_He3_other_eES_1e6.evio" \
# -USE_QT=0
# 
# gemc \
# -gcard=solid_CLEO_SIDIS_He3_other.gcard \
# -DBHOST=$GEMC_HOST \
# -HIT_PROCESS_LIST=solid \
# -HALL_MATERIAL=Vacuum \
# -USE_PHYSICSL=QGSP_BERT \
# -RECORD_PASSBY=1 \
# -FIELD_DIR=$GEMC_field \
# -HALL_FIELD=solenoid_CLEO \
# -INPUT_GEN_FILE="LUND,/home/zwzhao/work_halla/solid/solid_svn/solid/evgen/eicRate_20101102/output/SIDIS_He3/rate_solid_SIDIS_He3_eDIS_1e6.lund" \
# -N=1e6 \
# -OUTPUT="evio,background_solid_CLEO_SIDIS_He3_other_eDIS_1e6.evio" \
# -USE_QT=0


gemc_evio2root background_solid_CLEO_SIDIS_He3_other_pip_1e6.evio background_solid_CLEO_SIDIS_He3_other_pip_1e6.root
# gemc_evio2root background_solid_CLEO_SIDIS_He3_other_pim_1e6.evio background_solid_CLEO_SIDIS_He3_other_pim_1e6.root
# gemc_evio2root background_solid_CLEO_SIDIS_He3_other_pi0_1e6.evio background_solid_CLEO_SIDIS_He3_other_pi0_1e6.root
# gemc_evio2root background_solid_CLEO_SIDIS_He3_other_Kp_1e6.evio background_solid_CLEO_SIDIS_He3_other_Kp_1e6.root
# gemc_evio2root background_solid_CLEO_SIDIS_He3_other_Km_1e6.evio background_solid_CLEO_SIDIS_He3_other_Km_1e6.root
# gemc_evio2root background_solid_CLEO_SIDIS_He3_other_Ks_1e6.evio background_solid_CLEO_SIDIS_He3_other_Ks_1e6.root
# gemc_evio2root background_solid_CLEO_SIDIS_He3_other_Kl_1e6.evio background_solid_CLEO_SIDIS_He3_other_Kl_1e6.root
# gemc_evio2root background_solid_CLEO_SIDIS_He3_other_p_1e6.evio background_solid_CLEO_SIDIS_He3_other_p_1e6.root
# gemc_evio2root background_solid_CLEO_SIDIS_He3_other_eES_1e6.evio background_solid_CLEO_SIDIS_He3_other_eES_1e6.root
# gemc_evio2root background_solid_CLEO_SIDIS_He3_other_eDIS_1e6.evio background_solid_CLEO_SIDIS_He3_other_eDIS_1e6.root

root -b -q '/home/zwzhao/work_halla/solid/solid_svn/solid/solid_gemc/analysistool/background/root2hit.C("background_solid_CLEO_SIDIS_He3_other_pip_1e6.root")'
# root -b -q '/home/zwzhao/work_halla/solid/solid_svn/solid/solid_gemc/analysistool/background/root2hit.C("background_solid_CLEO_SIDIS_He3_other_pim_1e6.root")'
# root -b -q '/home/zwzhao/work_halla/solid/solid_svn/solid/solid_gemc/analysistool/background/root2hit.C("background_solid_CLEO_SIDIS_He3_other_pi0_1e6.root")'
# root -b -q '/home/zwzhao/work_halla/solid/solid_svn/solid/solid_gemc/analysistool/background/root2hit.C("background_solid_CLEO_SIDIS_He3_other_Kp_1e6.root")'
# root -b -q '/home/zwzhao/work_halla/solid/solid_svn/solid/solid_gemc/analysistool/background/root2hit.C("background_solid_CLEO_SIDIS_He3_other_Km_1e6.root")'
# root -b -q '/home/zwzhao/work_halla/solid/solid_svn/solid/solid_gemc/analysistool/background/root2hit.C("background_solid_CLEO_SIDIS_He3_other_Ks_1e6.root")'
# root -b -q '/home/zwzhao/work_halla/solid/solid_svn/solid/solid_gemc/analysistool/background/root2hit.C("background_solid_CLEO_SIDIS_He3_other_Kl_1e6.root")'
# root -b -q '/home/zwzhao/work_halla/solid/solid_svn/solid/solid_gemc/analysistool/background/root2hit.C("background_solid_CLEO_SIDIS_He3_other_p_1e6.root")'
# root -b -q '/home/zwzhao/work_halla/solid/solid_svn/solid/solid_gemc/analysistool/background/root2hit.C("background_solid_CLEO_SIDIS_He3_other_eES_1e6.root")'
# root -b -q '/home/zwzhao/work_halla/solid/solid_svn/solid/solid_gemc/analysistool/background/root2hit.C("background_solid_CLEO_SIDIS_He3_other_eDIS_1e6.root")'

# -N=1e6 \
# -OUTPUT="evio,background_solid_CLEO_SIDIS_He3_other_eDIS_1e6.evio" \
# -USE_QT=0

# -N=1e5 \
# -OUTPUT="evio,acceptance_solid_CLEO_PVDIS.evio" \
# -USE_QT=0

# -geometry=1000x1000 \
# -EXEC_MACRO=$SoLID_GEMC/script/solid_slice.vis \
# -USE_QT=1

# -CHECK_OVERLAPS=1 \
# -USE_QT=0
