/********************************************************************
* SolenoidDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error SolenoidDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableSolenoidDict();
extern void G__cpp_setup_inheritanceSolenoidDict();
extern void G__cpp_setup_typetableSolenoidDict();
extern void G__cpp_setup_memvarSolenoidDict();
extern void G__cpp_setup_globalSolenoidDict();
extern void G__cpp_setup_memfuncSolenoidDict();
extern void G__cpp_setup_funcSolenoidDict();
extern void G__set_cpp_environmentSolenoidDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "THaSolenoid.h"
#include "THaSoleGEMSim.h"
#include "THaSoleSimRun.h"
#include "THaSoleSimDecoder.h"
#include "SOLGEM.h"
#include "THaGemHit.h"
#include "THaGemTrack.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__SolenoidDictLN_TClass;
extern G__linked_taginfo G__SolenoidDictLN_TBuffer;
extern G__linked_taginfo G__SolenoidDictLN_TDirectory;
extern G__linked_taginfo G__SolenoidDictLN_TMemberInspector;
extern G__linked_taginfo G__SolenoidDictLN_TObject;
extern G__linked_taginfo G__SolenoidDictLN_TNamed;
extern G__linked_taginfo G__SolenoidDictLN_TString;
extern G__linked_taginfo G__SolenoidDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__SolenoidDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__SolenoidDictLN_TList;
extern G__linked_taginfo G__SolenoidDictLN_TClonesArray;
extern G__linked_taginfo G__SolenoidDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__SolenoidDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__SolenoidDictLN_THaRunBase;
extern G__linked_taginfo G__SolenoidDictLN_TDatime;
extern G__linked_taginfo G__SolenoidDictLN_THaEvData;
extern G__linked_taginfo G__SolenoidDictLN_THaAnalysisObject;
extern G__linked_taginfo G__SolenoidDictLN_THaAnalysisObjectcLcLEStatus;
extern G__linked_taginfo G__SolenoidDictLN_THaAnalysisObjectcLcLEMode;
extern G__linked_taginfo G__SolenoidDictLN_vectorlEstringcOallocatorlEstringgRsPgR;
extern G__linked_taginfo G__SolenoidDictLN_reverse_iteratorlEvectorlEstringcOallocatorlEstringgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__SolenoidDictLN_THaDetector;
extern G__linked_taginfo G__SolenoidDictLN_THaApparatus;
extern G__linked_taginfo G__SolenoidDictLN_TMatrixTBaselEfloatgR;
extern G__linked_taginfo G__SolenoidDictLN_TMatrixTBaselEdoublegR;
extern G__linked_taginfo G__SolenoidDictLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__SolenoidDictLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__SolenoidDictLN_TElementActionTlEfloatgR;
extern G__linked_taginfo G__SolenoidDictLN_TElementPosActionTlEfloatgR;
extern G__linked_taginfo G__SolenoidDictLN_TElementActionTlEdoublegR;
extern G__linked_taginfo G__SolenoidDictLN_TElementPosActionTlEdoublegR;
extern G__linked_taginfo G__SolenoidDictLN_TMatrixTlEfloatgR;
extern G__linked_taginfo G__SolenoidDictLN_TMatrixTRow_constlEfloatgR;
extern G__linked_taginfo G__SolenoidDictLN_TMatrixTRowlEfloatgR;
extern G__linked_taginfo G__SolenoidDictLN_TMatrixTDiag_constlEfloatgR;
extern G__linked_taginfo G__SolenoidDictLN_TMatrixTColumn_constlEfloatgR;
extern G__linked_taginfo G__SolenoidDictLN_TMatrixTFlat_constlEfloatgR;
extern G__linked_taginfo G__SolenoidDictLN_TMatrixTSub_constlEfloatgR;
extern G__linked_taginfo G__SolenoidDictLN_TMatrixTSparseRow_constlEfloatgR;
extern G__linked_taginfo G__SolenoidDictLN_TMatrixTSparseDiag_constlEfloatgR;
extern G__linked_taginfo G__SolenoidDictLN_TMatrixTColumnlEfloatgR;
extern G__linked_taginfo G__SolenoidDictLN_TMatrixTDiaglEfloatgR;
extern G__linked_taginfo G__SolenoidDictLN_TMatrixTFlatlEfloatgR;
extern G__linked_taginfo G__SolenoidDictLN_TMatrixTSublEfloatgR;
extern G__linked_taginfo G__SolenoidDictLN_TMatrixTSparseRowlEfloatgR;
extern G__linked_taginfo G__SolenoidDictLN_TMatrixTSparseDiaglEfloatgR;
extern G__linked_taginfo G__SolenoidDictLN_THaVertexModule;
extern G__linked_taginfo G__SolenoidDictLN_THaSpectrometer;
extern G__linked_taginfo G__SolenoidDictLN_THaTrackingModule;
extern G__linked_taginfo G__SolenoidDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__SolenoidDictLN_THaSoleSimTrack;
extern G__linked_taginfo G__SolenoidDictLN_THaSoleSimHit;
extern G__linked_taginfo G__SolenoidDictLN_THaSoleSimEvent;
extern G__linked_taginfo G__SolenoidDictLN_TFile;
extern G__linked_taginfo G__SolenoidDictLN_TTree;
extern G__linked_taginfo G__SolenoidDictLN_THaSoleSimRun;
extern G__linked_taginfo G__SolenoidDictLN_THaCrateMap;
extern G__linked_taginfo G__SolenoidDictLN_THaDetectorBase;
extern G__linked_taginfo G__SolenoidDictLN_vectorlEintcOallocatorlEintgRsPgR;
extern G__linked_taginfo G__SolenoidDictLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__SolenoidDictLN_TMatrixTlEdoublegR;
extern G__linked_taginfo G__SolenoidDictLN_TMatrixTSymlEdoublegR;
extern G__linked_taginfo G__SolenoidDictLN_TMatrixTRow_constlEdoublegR;
extern G__linked_taginfo G__SolenoidDictLN_TMatrixTRowlEdoublegR;
extern G__linked_taginfo G__SolenoidDictLN_TMatrixTDiag_constlEdoublegR;
extern G__linked_taginfo G__SolenoidDictLN_TMatrixTColumn_constlEdoublegR;
extern G__linked_taginfo G__SolenoidDictLN_TMatrixTFlat_constlEdoublegR;
extern G__linked_taginfo G__SolenoidDictLN_TMatrixTSub_constlEdoublegR;
extern G__linked_taginfo G__SolenoidDictLN_TMatrixTSparseRow_constlEdoublegR;
extern G__linked_taginfo G__SolenoidDictLN_TMatrixTSparseDiag_constlEdoublegR;
extern G__linked_taginfo G__SolenoidDictLN_TMatrixTColumnlEdoublegR;
extern G__linked_taginfo G__SolenoidDictLN_TMatrixTDiaglEdoublegR;
extern G__linked_taginfo G__SolenoidDictLN_TMatrixTFlatlEdoublegR;
extern G__linked_taginfo G__SolenoidDictLN_TMatrixTSublEdoublegR;
extern G__linked_taginfo G__SolenoidDictLN_TMatrixTSparseRowlEdoublegR;
extern G__linked_taginfo G__SolenoidDictLN_TMatrixTSparseDiaglEdoublegR;
extern G__linked_taginfo G__SolenoidDictLN_THaSolenoid;
extern G__linked_taginfo G__SolenoidDictLN_THaSoleSimDecoder;
extern G__linked_taginfo G__SolenoidDictLN_THaSpectrometerDetector;
extern G__linked_taginfo G__SolenoidDictLN_THaTrackingDetector;
extern G__linked_taginfo G__SolenoidDictLN_THaGemHit;
extern G__linked_taginfo G__SolenoidDictLN_THaGemTrack;
extern G__linked_taginfo G__SolenoidDictLN_SOLGEM;

/* STUB derived class for protected member access */
