#!/bin/tcsh
#source this script to setup solid_gemc software

#default jlabce version, or use command option to use other version
setenv JLAB_VERSION 2.5
if( "$1" != "" ) setenv JLAB_VERSION $1

setenv JLAB_ROOT /jlab
if( "$2" != "" ) setenv JLAB_ROOT $2

#default repo, change it to your location
setenv SoLID_GEMC /solid_gemc 
# setenv SoLID_GEMC /solid/solid_gemc # default in container for 1.3
if( "$3" != "" ) setenv SoLID_GEMC $3

#no need to modify variables below generally
#========================================================================
source $JLAB_ROOT/$JLAB_VERSION/ce/jlab.csh       #setup basic environment variables 

# add path for "libgemc.so"
if( "$JLAB_VERSION" == "1.2" || "$JLAB_VERSION" == "1.3"  ) setenv LD_LIBRARY_PATH ${GEMC}/source:${LD_LIBRARY_PATH}   
else setenv LD_LIBRARY_PATH ${GEMC}:${LD_LIBRARY_PATH}
endif

# add path for "solid_gemc" binary
setenv PATH ${SoLID_GEMC}/source/${GEMC_VERSION}:${PATH} 
