#!/bin/tcsh
#source this script to setup SoLID software

#default SVN checkout on ifarm and farm nodes, change it to your local SVN checkout location if you want to use it
setenv SoLID_GEMC /group/solid/solid_svn/solid_gemc2 #solid_gemc location

#the default version, or use command option to use other version
setenv JLAB_VERSION 1.3
if( "$1" != "" ) setenv JLAB_VERSION $1

#default installation on ifarm and farm nodes, comment this out for your installation
if( "$JLAB_VERSION" == "1.2" || "$JLAB_VERSION" == "1.3"  ) setenv JLAB_ROOT /group/solid/apps/jlab_root
if( "$JLAB_VERSION" == "2.0" || "$JLAB_VERSION" == "2.2" || "$JLAB_VERSION" == "devel" ) setenv JLAB_ROOT /site/12gev_phys
#uncomment this for your_installation_path, the path below is just an example
#setenv JLAB_ROOT /home/$USER/apps/jlab_root

#no need to modify variables below generally
#========================================================================
source $JLAB_ROOT/$JLAB_VERSION/ce/jlab.csh       #setup basic enviroment variables 

# add path for "libgemc.so"
if( "$JLAB_VERSION" == "1.2" || "$JLAB_VERSION" == "1.3"  ) setenv LD_LIBRARY_PATH ${GEMC}/source:${LD_LIBRARY_PATH}   
if( "$JLAB_VERSION" == "2.0" || "$JLAB_VERSION" == "2.2" || "$JLAB_VERSION" == "devel" ) setenv LD_LIBRARY_PATH ${GEMC}:${LD_LIBRARY_PATH}

# add path for "solid_gemc" binary
setenv PATH ${SoLID_GEMC}/source/${GEMC_VERSION}:${PATH} 

setenv GEMC_HOST soliddb.jlab.org   #use this if your system is on jlab network
#setenv GEMC_HOST 127.0.0.1       #use this if you are tunnleing to access mysql server
setenv GEMC_DB solid_geometry       #the official detector database
setenv GEMC_BANK solid_banks        #the official output bank info
#setenv GEMC_DB   test              #user geometry for test
#setenv GEMC_BANK test              #user banks for test
setenv GEMC_USER soliduser          #this user only can read database, used for run simulation
setenv GEMC_PASS ilovesolid         #readonly user password
#setenv GEMC_USER soliddev          #this user can read and write, used for update database
#setenv GEMC_PASS                   #ask other solid gemc develeoper for this password
