#!/bin/csh
#uname -a | cat > out.log
#more /etc/redhat-release | cat >> out.log
#more /proc/cpuinfo | cat >> out.log
#more /proc/meminfo | cat >> out.log

#use official installation on farm and ifarm
#setenv LD_LIBRARY_PATH /home/${USER}/lib
#setenv LIBRARY_PATH /home/${USER}/lib
source /home/zwzhao/set_solid_1.2_mine

#run generator
#/home/zwzhao/solid/solid_svn/solid/evgen/eicRate_20101102/eicRate -i input.dat -o gen.root -n 1e4 -m 0

#run simulation
# gemc solid.gcard | cat >> out.log
solid_gemc tracking_solid_SIDIS_He3_single.gcard -PRINT_EVENT=1000 -BEAM_P="pi-,5.5*GeV,15*deg,0*deg" -SPREAD_P="5.5*GeV,10*deg,180*deg" -BEAM_V="(0,0,-350)cm" -SPREAD_V="(0.21,20)cm" -N="1e5" -OUTPUT="evio,tracking_solid_SIDIS_He3_pim_1e5.evio" -USE_GUI=0

#convert evio to root
#need more option for banks other than flux
evio2root -INPUTF=tracking_solid_SIDIS_He3_pim_1e5.evio -B="/home/zwzhao/solid/solid_svn/solid/solid_gemc2/geometry/ec/solid_SIDIS_ec_forwardangle /home/zwzhao/solid/solid_svn/solid/solid_gemc2/geometry/ec/solid_SIDIS_ec_largeangle /home/zwzhao/solid/solid_svn/solid/solid_gemc2/geometry/hgc/solid_SIDIS_hgc /home/zwzhao/solid/solid_svn/solid/solid_gemc2/geometry/lgc/solid_SIDIS_lgc /home/zwzhao/solid/solid_svn/solid/solid_gemc2/geometry/hgc/solid_SIDIS_hgc /home/zwzhao/solid/solid_svn/solid/solid_gemc2/geometry/gem/solid_SIDIS_gem /home/zwzhao/solid/solid_svn/solid/solid_gemc2/geometry/mrpc/solid_SIDIS_mrpc_forwardangle /home/zwzhao/solid/solid_svn/solid/solid_gemc2/geometry/spd/solid_SIDIS_spd_forwardangle /home/zwzhao/solid/solid_svn/solid/solid_gemc2/geometry/spd/solid_SIDIS_spd_largeangle" 



