#!/bin/sh
gemc \
-gcard=solid_CLEO_SIDIS_3he.gcard \
-DBHOST=$GEMC_HOST \
-HALL_MATERIAL=Vacuum \
-RECORD_PASSBY=1 \
-FIELD_DIR=$GEMC_field \
-HALL_FIELD=solenoid_CLEO \
-BEAM_P="chargedgeantino, 5.5*GeV, 20*deg, 0*deg" \
-SPREAD_P="5.5*GeV, 20*deg, 180*deg" \
-BEAM_V="(0, 0, -350)cm" \
-SPREAD_V="(0.21, 20)cm" \
-N=1e6 \
-OUTPUT="evio,acceptance_solid_CLEO_SIDIS_3he_positive.evio" \
-USE_QT=0

gemc_evio2root acceptance_solid_CLEO_SIDIS_3he_positive.evio acceptance_solid_CLEO_SIDIS_3he_positive.root

#-HIT_VERBOSITY=100 \
# -OUT_VERBOSITY=5 \
# -geometry=1000x1000 \
# -EXEC_MACRO=$SoLID_GEMC/script/solid_slice.vis \
# -USE_QT=1 

# -N=1e5 \
# -OUTPUT="evio,acceptance_solid_CLEO_SIDIS_3he.evio" \
# -USE_QT=0

# -HIT_VERBOSITY=100 \
# -OUT_VERBOSITY=5 \
# -CHECK_OVERLAPS=1 \
# -USE_QT=0