#!/usr/bin/python 
from init_env import init_environment

import os

env = init_environment("evio qt4 geant4 clhep")

# Get GEMC path
gemcpath = os.environ['GEMC']+'/'
env.Append(LIBPATH = gemcpath);
# LIBPATH here is what GEMC used to link all the libraries to gemc.so
rpath = env['LIBPATH']


# Include Path
incpath = ['.',gemcpath, gemcpath+'src', gemcpath+'gui/src', 'src', 'gui/src']
env.Append(CPPPATH = incpath)

# Sources
gemc_sources = Split("""solgemc.cc
			src/SolPrimaryGeneratorAction.cc""")

# Physics
phys_sources = Split("""physics/SolidNoPhysicsList.cc
			physics/SolidNoPhysics.cc""")

incpath = [gemcpath+'physics', 'physics']
env.Append(CPPPATH = incpath)


# Hit Processes
hitp_sources = Split("""hitprocess/trace_HitProcess.cc
	                hitprocess/sbsgem_HitProcess.cc""")
                        
incpath = [gemcpath+'hitprocess', gemcpath+'hitprocess/clas12', gemcpath+'hitprocess/clas12/svt', gemcpath+'hitprocess/clas12/micromegas', gemcpath+'hitprocess/Aprime', gemcpath+'hitprocess/GlueX','hitprocess']
env.Append(CPPPATH = incpath)

# Outputs
output_sources = Split("""""")
incpath = [gemcpath+'output', 'output']
env.Append(CPPPATH = incpath)

env.Append(LIBS = "gemc");

Target = 'solgemc'
env.Program(source = gemc_sources + phys_sources + hitp_sources + output_sources, target = Target)
