#
# Macro file for the initialization phase of "exampleN02.cc"
# when runing in interactive mode
#
# Sets some default verbose
#
# run with /control/execute mac/TestFile.mac
#
/control/verbose 2
/run/verbose 2
/event/verbose 2
/tracking/verbose 2


/particle/list
/process/list


/Gun/InputBeamParticle e-

/Gun/UseFile 1
/Gun/inputFile script/electron_BaBar.track.dat
# /Gun/inputFile script/test.track.dat

/Gun/UseMagneticField 0 1.5 0

/run/beamOn 1
