#!/usr/bin/perl
# Perl module to run 
############################################################
print "mkdir at volatile disk\n";
$cdir = `pwd`;
$odir = $cdir =~ s/w\/halla-scifs17exp/volatile\/halla/r;
system("mkdir -p $odir");

print "Give the start run number [2000]\n";
$srunnum = <STDIN>;
chop($srunnum);

print "Give the end run number [2010]\n";
$erunnum = <STDIN>;
chop($erunnum);

if($srunnum<=$erunnum){
    for($i=$srunnum;$i<=$erunnum;$i++){
	print `./exec_sim -r$i  \n`;
    }
}
else {
    die "End run number should be greater than start run number\n";
}
