#
# Macro file for running mulan quietly
#
#
# Sets some default verbose
#

/control/verbose 0
/run/verbose 0
#/gun/energy 1 MeV

#/mygen/inputFile /scratch/charm/rmcnabb/electrons.dat


/mygen/Energy 1
/mygen/Angle 20





#/vis/scene/create

#/vis/open VRML1

# /vis/viewer/viewpointThetaPhi -60 -5 deg


#/vis/drawVolume
#/vis/viewer/refresh
#/vis/viewer/update 



#/tracking/storeTrajectory 1
#/vis/scene/add/trajectories

/run/beamOn 5000





