#!/bin/sh
for mom in 2.5 3.0 3.5 4.0 4.5 5.0 5.5 6.0 6.5 7.0 7.5
do
   for theta in 7.5 8.0 14.8
   do
    solid_gemc solid_SIDIS_He3_hgc_moved_batch.gcard -BEAM_P="pi-,$mom*GeV,$theta*deg,0*deg" -BEAM_V="(0,0,-350)cm" -NO_FIELD="all" -OUTPUT=evio,output/output_pim_z0_p$mom\_theta$theta\_phi0_blockoff_fieldoff_1e3.evio -N=1e3
    evio2root -INPUTF=output/output_pim_z0_p$mom\_theta$theta\_phi0_blockoff_fieldoff_1e3.evio  -B="../hgc_solid_gemc/solid_SIDIS_hgc"
   done
done



