#!/bin/tcsh
#this is just an example script to setup SoLID GEMC on local machine
#modify the variables to your path and source it to setup
#by default, gemc is its current production version by default in jlab.csh, to run the production version for SoLID gemc, we need to specify its version by set the env variables explicitly, currently its gemc version 1.7
setenv GEANT4_VERSION 4.9.5.p01
setenv CLHEP_VERSION 2.1.2.0
setenv ROOT_VERSION 5.32
setenv QT_VERSION 4.8.1
setenv GEMC_VERSION 1.7
setenv JLAB_ROOT jlab_root_path  #setup basic enviroment variables for gemc on local installation (modify this to your path)
source $JLAB_ROOT/ce/jlab.csh    
setenv SoLID_GEMC solid_gemc_path #solid_gemc location where you download from SoLID SVN (modify this to your path)
setenv GEMC_field field_path        #location of GEMC field map on local (modify this to your path)
setenv GEMC_HOST 127.0.0.1          #use this after ssh tunneling if your system is NOT on jlab network (modify choose this one or the other)
#setenv GEMC_HOST soliddb.jlab.org  #use this if your system is on jlab network and no need tunneling (modify choose this one or the other)
setenv GEMC_DB solid_geometry       #the official detector database
setenv GEMC_BANK solid_banks        #the official output bank info
#setenv GEMC_DB   test              #user geometry for test
#setenv GEMC_BANK test              #user banks for test
setenv GEMC_USER soliduser          #this user only can read database, used for run simulation
setenv GEMC_PASS ilovesolid         #readonly user password
#setenv GEMC_USER soliddev          #this user can read and write, used for update database
#setenv GEMC_PASS                   #ask other solid gemc develeoper for this password
