#!/bin/tcsh -f
root -l -b -q  'analysis_SIDIS.C+("/cache/halla/solid/sim/solid_gemc/SIDIS_He3_JLAB_VERSION_1.3/pass7/background_solid_SIDIS_He3_BeamOnTarget_0.999e10_skim.root","trigger",false,"single")'
root -l -b -q  'analysis_SIDIS.C+("/cache/halla/solid/sim/solid_gemc/SIDIS_He3_JLAB_VERSION_1.3/pass7/background_solid_SIDIS_He3_BeamOnTargetEM_1e10_skim.root","trigger",false,"single")'

root -l -b -q  'analysis_SIDIS.C+("/cache/halla/solid/sim/solid_gemc/SIDIS_He3_JLAB_VERSION_1.3/pass7/background_solid_SIDIS_He3_dirty_weighted_eDIS_filenum50_0.5e6.root","trigger",false,"single")'

root -l -b -q  'analysis_SIDIS.C+("/cache/halla/solid/sim/solid_gemc/SIDIS_He3_JLAB_VERSION_1.3/pass7/background_solid_SIDIS_He3_dirty_normalized_pipHallD_filenum500_5e6.root","trigger",false,"single")'
root -l -b -q  'analysis_SIDIS.C+("/cache/halla/solid/sim/solid_gemc/SIDIS_He3_JLAB_VERSION_1.3/pass7/background_solid_SIDIS_He3_dirty_normalized_pimHallD_filenum500_5e6.root","trigger",false,"single")'
root -l -b -q  'analysis_SIDIS.C+("/cache/halla/solid/sim/solid_gemc/SIDIS_He3_JLAB_VERSION_1.3/pass7/background_solid_SIDIS_He3_dirty_normalized_pi0HallD_filenum500_5e6.root","trigger",false,"single")'
root -l -b -q  'analysis_SIDIS.C+("/cache/halla/solid/sim/solid_gemc/SIDIS_He3_JLAB_VERSION_1.3/pass7/background_solid_SIDIS_He3_dirty_normalized_pHallD_filenum500_5e6.root","trigger",false,"single")'
root -l -b -q  'analysis_SIDIS.C+("/cache/halla/solid/sim/solid_gemc/SIDIS_He3_JLAB_VERSION_1.3/pass7/background_solid_SIDIS_He3_dirty_normalized_allnoeHallD_filenum250_2.5e6.root","trigger",false,"single")'




# root -l -b -q  'analysis_SIDIS.C+("/cache/halla/solid/sim/solid_gemc/SIDIS_He3_JLAB_VERSION_1.3/pass7/background_solid_SIDIS_He3_dirty_weighted_SIDISDuke_epip_filenum75_0.375e6.root","trigger",false,"sidis")'
# root -l -b -q  'analysis_SIDIS.C+("/cache/halla/solid/sim/solid_gemc/SIDIS_He3_JLAB_VERSION_1.3/pass7/background_solid_SIDIS_He3_dirty_weighted_SIDISDuke_epim_filenum75_0.375e6.root","trigger",false,"sidis")'
# root -l -b -q  'analysis_SIDIS.C+("/cache/halla/solid/sim/solid_gemc/SIDIS_He3_JLAB_VERSION_1.3/pass7/background_solid_SIDIS_He3_dirty_weighted_SIDISDuke_epi0_filenum75_0.375e6.root","trigger",false,"sidis")'
# root -l -b -q  'analysis_SIDIS.C+("/cache/halla/solid/sim/solid_gemc/SIDIS_He3_JLAB_VERSION_1.3/pass7/background_solid_SIDIS_He3_dirty_weighted_SIDISDuke_ep_filenum75_0.375e6.root","trigger",false,"sidis")'

# root -l -b -q 'analysis_SIDIS.C+("/cache/halla/solid/sim/solid_gemc/SIDIS_He3_JLAB_VERSION_1.3/pass7/background_solid_SIDIS_He3_dirty_weighted_SIDISDuke_epip_filenum75_0.375e6.root","trigger",false,"sidis")'

# root -l -b -q 'analysis_SIDIS.C+("/cache/halla/solid/sim/solid_gemc/SIDIS_He3_JLAB_VERSION_1.3/pass7/background_solid_SIDIS_He3_dirty_normalized_SIDISDuke_epip_filenum75_0.375e6.root","trigger",false,"sidis")'
