#!/bin/tcsh -f

root -l -b -q  'analysis_SIDIS.C+("/cache/halla/solid/sim/solid_gemc/SIDIS_NH3_JLAB_VERSION_1.3/pass6/solid_SIDIS_NH3_dirty_weighted_eDIS_filenum412_4.12e6_skim.root","trigger",false,"single")'
root -l -b -q  'analysis_SIDIS.C+("/cache/halla/solid/sim/solid_gemc/SIDIS_NH3_JLAB_VERSION_1.3/pass3/solid_SIDIS_NH3_dirty_normalized_pi0Wiser_filenum499_4.99e6_skim.root","trigger",false,"single")'
root -l -b -q  'analysis_SIDIS.C+("/cache/halla/solid/sim/solid_gemc/SIDIS_NH3_JLAB_VERSION_1.3/pass3/solid_SIDIS_NH3_dirty_normalized_pimWiser_filenum494_4.94e6_skim.root","trigger",false,"single")'
root -l -b -q  'analysis_SIDIS.C+("/cache/halla/solid/sim/solid_gemc/SIDIS_NH3_JLAB_VERSION_1.3/pass3/solid_SIDIS_NH3_dirty_normalized_pipWiser_filenum497_4.97e6_skim.root","trigger",false,"single")'
root -l -b -q  'analysis_SIDIS.C+("/cache/halla/solid/sim/solid_gemc/SIDIS_NH3_JLAB_VERSION_1.3/pass3/solid_SIDIS_NH3_dirty_normalized_pWiser_filenum100_1e6_skim.root","trigger",false,"single")'

